-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 15:53:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema snakesAndLaddersData
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema snakesAndLaddersData
-- -----------------------------------------------------
SET GLOBAL log_bin_trust_function_creators = 1;
CREATE SCHEMA IF NOT EXISTS `snakesandladdersdatabase` DEFAULT CHARACTER SET utf8 ;
USE `snakesandladdersdatabase` ;



-- DROP database if exists snakesandladdersdatabase;


----------------------------------------------------------------------------------
--
--
-- TABLE CREATIONS
-- 
--
-- ----------------------------------------------------------------------------------
-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Dice`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS dice (
  `diceID` INTEGER NOT NULL AUTO_INCREMENT,
  `diceCount` INT NOT NULL,
  `diceFaces` INT NOT NULL,
  PRIMARY KEY (`DiceID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Game`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS game (
  `gameID` INT NOT NULL AUTO_INCREMENT,
  `gamePlayerTurn` INT NOT NULL DEFAULT 1,
  `gameRound` INT NOT NULL DEFAULT 1,
  `boardGridSize` INT NOT NULL,
  `boardSize` INT NOT NULL DEFAULT 16,
--   `winningSquare` INT NULL,
  `gameHasEnded` TINYINT NULL DEFAULT false,
  `boostSquareFeature` TINYINT NULL DEFAULT false,
  `winningSquareOnlyFeature` TINYINT NULL DEFAULT false,
  `recordGameFeature` TINYINT NULL DEFAULT false,
  `dice_diceID` INT NOT NULL,
  PRIMARY KEY (`gameID`),
    FOREIGN KEY (`dice_diceID`)
    REFERENCES dice (`diceID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Players`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS players (
  `playerID` INT NOT NULL AUTO_INCREMENT,
  `playerColour` VARCHAR(45) NOT NULL,
  `playerPosition` INT DEFAULT 0,
  `playerMovesTaken` INT DEFAULT 0,
  `playerWonGame` TINYINT DEFAULT false,
  `game_gameID` INT NOT NULL,
  `pl_PlayerListID`INT NULL,
  PRIMARY KEY (playerID),
    FOREIGN KEY (game_gameID)
    REFERENCES game(gameID),
    FOREIGN KEY (pl_PlayerListID)
    REFERENCES PlayerList (PlayerListID)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`PlayerList`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS playerList (
	`playerListID` INT NOT NULL AUTO_INCREMENT,
    `playerColour` VARCHAR(45),
    `playerWinCount` INT DEFAULT 0,
    `playerTotalMovesMade` INT DEFAULT 0,
    `playerAverageGameMoves` DECIMAL (4,2),
    PRIMARY KEY (`playerListID`))
ENGINE = InnoDB;
        
-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`snakes`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS snakes (
  `snakeID` INT NOT NULL AUTO_INCREMENT,
  `snakeHead` INT NOT NULL,
  `snakeTail` INT NOT NULL,
  `game_gameID` INT NOT NULL,
  PRIMARY KEY (`snakeID`),
    FOREIGN KEY (`game_gameID`)
    REFERENCES game (`gameID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Ladders`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ladders (
  `ladderID` INT NOT NULL AUTO_INCREMENT,
  `ladderFoot` INT NOT NULL,
  `ladderTop` INT NOT NULL,
  `game_gameID` INT NOT NULL,
  PRIMARY KEY (`ladderID`),
    FOREIGN KEY (`game_gameID`)
    REFERENCES game (`gameID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Boosts`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS boosts (
  `boostID` INT NOT NULL AUTO_INCREMENT,
  `boostLocation` INT NOT NULL,
  `game_gameID` INT NOT NULL,
  PRIMARY KEY (`boostID`),
    FOREIGN KEY (`Game_gameID`)
    REFERENCES game (`gameID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `snakesAndLaddersData`.`Moves`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS moves (
  `moveID` INT NOT NULL AUTO_INCREMENT,
  `moveStart` INT NOT NULL,
  `moveEnd` INT NOT NULL,
  `moveRoll` INT,
  `landedOnSnake` TINYINT DEFAULT 0,
  `landedOnLadder`TINYINT DEFAULT 0,
  `landedOnBoost`TINYINT DEFAULT 0,
  `players_playerID` INT NOT NULL,
  `game_gameID` INT NOT NULL,
  PRIMARY KEY (`moveID`),
    FOREIGN KEY (`players_playerID`)
    REFERENCES players (`playerID`),
    FOREIGN KEY (`game_gameID`)
    REFERENCES game (`gameID`))
ENGINE = InnoDB;

-- CREATE TABLE IF NOT EXISTS databaseEnabled (
-- 	isDatabaseOn TINYINT DEFAULT 0
--     );

-- ----------------------------------------------------------------------------------
--
--
-- GAME PROCEDURES
-- 
--
-- ----------------------------------------------------------------------------------


-- -----------------------------------------------------
-- Procedure passes in new Player data from call into table. 
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_player;

DELIMITER //

CREATE PROCEDURE add_new_player (IN newPlayerEntry VARCHAR(45))
BEGIN

	INSERT INTO PlayerList(playerColour)
	VALUES (newPlayerEntry);
END //
DELIMITER ;


-- -----------------------------------------------------
-- Procedure adds a new blank game state. 
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_game;

DELIMITER //
CREATE PROCEDURE add_new_game(IN chosenBoardSize INT, IN chosenDice INT)
BEGIN

	INSERT INTO game(boardSize,boardGridSize, dice_diceID)
    VALUES(chosenBoardSize*chosenBoardSize,chosenBoardSize, chosenDice);
END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure adds a new game state. 
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_game;

DELIMITER //
CREATE PROCEDURE add_new_game(IN chosenBoardSize INT, IN chosenDiceCount INT, IN chosenDiceFace INT)
BEGIN
    CALL add_new_dice(chosenDiceCount, chosenDiceFace);
	INSERT INTO Game(boardSize,boardGridSize, dice_diceID)
    VALUES(chosenBoardSize*chosenBoardSize,chosenBoardSize, (SELECT MAX(diceID) from Dice));
    

END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure adds new player to a blank game state.
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_player_to_game;
DELIMITER //
CREATE PROCEDURE add_new_player_to_game(IN playerColourChoice VARCHAR(45), IN gameStateChoice INT, IN savedPlayerChoice INT)
BEGIN
	SET FOREIGN_KEY_CHECKS=0;
	INSERT INTO players(playerColour, game_gameID, pl_PlayerListID)
    VALUES(playerColourChoice, gameStateChoice, savedPlayerChoice);
    SET FOREIGN_KEY_CHECKS=1;

END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure passes in new Dice from call into table.
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_dice;

DELIMITER //
CREATE PROCEDURE add_new_dice(IN newDiceCount INT, IN newDiceFaces INT)
BEGIN

-- 	DECLARE incorrectDiceEntry CONDITION FOR 1357;
--     
--     DECLARE CONTINUE HANDLER FOR incorrectDiceEntry
-- 	SELECT 'INCORRECT dice choice made for new game.';

	INSERT INTO Dice (diceCount, diceFaces)
    VALUES (newDiceCount, newDiceFaces);
END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure passes in snake data from call into table. gameID pulled from last field created. 
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_snake;

DELIMITER //
CREATE PROCEDURE add_new_snake(IN newSnakeHead INT, IN newSnakeTail INT, IN gameChoice INT)
BEGIN

	INSERT INTO snakes(snakeHead, snakeTail, Game_gameID)
	VALUES (newSnakeHead, newSnakeTail, gameChoice);
END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure passes in Ladder data from call into table. gameID pulled from last field created. 
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS add_new_ladder;

DELIMITER //
CREATE PROCEDURE add_new_ladder(IN newLadderFoot INT, IN newLadderTop INT, IN gameChoice INT)
BEGIN
    
	INSERT INTO ladders(ladderFoot, ladderTop, Game_gameID)
	VALUES (newLadderFoot, newLadderTop, gameChoice);
END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure passes in Boost data from call into table. gameID pulled from last field created. 
-- -----------------------------------------------------
DROP PROCEDURE IF EXISTS add_new_boost;

DELIMITER //
CREATE PROCEDURE add_new_boost (IN boostLocation int, IN gameChoice INT)
BEGIN

	INSERT INTO boosts(boostLocation, Game_gameID)
	VALUES (boostLocation, gameChoice);
END //
DELIMITER ;

-- -----------------------------------------------------
-- Procedure saves a player's move during turn into table.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS add_player_move;

DELIMITER //
CREATE PROCEDURE add_player_move(IN playerTurnStart INT, IN playerTurnEnd INT, IN currentPlayer INT, IN currentGame INT)
BEGIN
	INSERT INTO moves (moveStart, moveEnd, players_playerID, game_gameID)
    VALUES (playerTurnStart, playerTurnEnd, currentPlayer, currentGame);

END //
DELIMITER ;


-- -----------------------------------------------------
-- grabs game based on ID choice .
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_game;

DELIMITER ££
CREATE PROCEDURE select_game (gameChoice INT, OUT gameNumber INT)
BEGIN

SELECT * FROM game WHERE gameID = gameChoice;

SELECT gameID INTO gameNumber
FROM game
where gameID = gameChoice;

END ££
DELIMITER ;

-- -----------------------------------------------------
-- grabs player data based on current game choice.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_players_from_game;

DELIMITER //

CREATE PROCEDURE select_players_from_game(IN currentgame INT)
BEGIN
	SELECT 
    playerColour,  
    playerPosition, 
    playerMovesTaken
    FROM players
    WHERE game_gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- grabs dice choice based on current game choice.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_dice_choice_from_game;

DELIMITER //

CREATE PROCEDURE select_dice_choice_from_game(IN currentgame INT)
BEGIN
	SELECT diceID, diceCount, diceFaces 
    FROM dice d
    INNER JOIN game g ON d.diceID = g.dice_diceID
    WHERE g.gameID = currentGame;
END //
DELIMITER ;



-- -----------------------------------------------------
-- Edits snake in game based upon entry.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_snake;

DELIMITER //

CREATE PROCEDURE update_snake(IN id INT, IN newSnakeHead INT, IN newSnakeTail INT)
BEGIN
	UPDATE snakes
    SET snakeHead = newSnakeHead, snakeTail = newSnakeTail WHERE snakeID = id;

END //
DELIMITER ;

-- -----------------------------------------------------
-- Edits ladder in game based upon entry.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_ladder;

DELIMITER //

CREATE PROCEDURE update_ladder(IN id INT, IN newLadderFoot INT, IN newLadderTop INT)
BEGIN
	UPDATE ladders
    SET ladderFoot = newLadderFoot, ladderTop = newLadderTop WHERE ladderID = id;

END //
DELIMITER ;

-- -----------------------------------------------------
-- Edits boost in game based upon entry.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_boost;

DELIMITER //

CREATE PROCEDURE update_boost(IN id INT, IN newBoostLocation INT)
BEGIN
	UPDATE boosts
    SET boostLocation = newBoostLocation WHERE boostID = id;

END //
DELIMITER ;

-- -----------------------------------------------------
-- Edits player name in database based upon entry.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_player;

DELIMITER //

CREATE PROCEDURE update_player(IN id INT, IN newPlayerColour VARCHAR(45))
BEGIN
	UPDATE playerList
    SET playerColour = newPlayerColour WHERE playerListID = id;

END //
DELIMITER ;

-- -----------------------------------------------------
-- Edits dice in game based upon entry.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_Dice;

DELIMITER //

CREATE PROCEDURE update_Dice(IN id INT, IN newDiceCount INT, IN newDiceFace INT)
BEGIN
	UPDATE dice
    SET diceCount = newDiceCount, diceFaces = newDiceFace WHERE diceID = id;

END //
DELIMITER ;



-- -----------------------------------------------------
-- grabs all snakes from current game choice.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_game_snakes;

DELIMITER //

CREATE PROCEDURE select_game_snakes(IN currentgame INT)
BEGIN
	SELECT * 
    FROM snakes
    WHERE game_gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- grabs all ladders from current game choice.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_game_ladders;

DELIMITER //

CREATE PROCEDURE select_game_ladders(IN currentgame INT)
BEGIN
	SELECT * 
    FROM ladders
    WHERE game_gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- grabs all boosts from current game choice.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS select_game_boosts;

DELIMITER //
CREATE PROCEDURE select_game_boosts(IN currentgame INT)
BEGIN
	SELECT * 
    FROM boosts
    WHERE game_gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- sets boost feature to true.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS switch_on_boost_feature;

DELIMITER //
CREATE PROCEDURE switch_on_boost_feature(IN currentGame INT)
BEGIN
	UPDATE game
	SET boostSquareFeature = true WHERE gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- sets winningSquare feature to true.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS switch_on_winning_feature;

DELIMITER //
CREATE PROCEDURE switch_on_winning_feature(IN currentGame INT)
BEGIN
	UPDATE game
	SET winningSquareOnlyFeature = true WHERE gameID = currentGame;
END //
DELIMITER ;

-- -----------------------------------------------------
-- Change player's position in game.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_player_position;

DELIMITER //
CREATE PROCEDURE update_player_position(IN colour VARCHAR(45), IN currentGame INT, IN newPosition INT)
BEGIN
	UPDATE Players
	SET playerPosition = newPosition WHERE game_gameID = currentGame
    AND playerColour = colour;
END //
DELIMITER ;

-- -----------------------------------------------------
-- Manually mark game as ended.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS manually_update_gameover;

DELIMITER //
CREATE PROCEDURE manually_update_gameover(IN currentGame INT)
BEGIN
	UPDATE game
	SET gameHasEnded = true WHERE gameID = currentGame;
END //
DELIMITER ;

-- ----------------------------------------------------------------------------------
--
--
-- GAME TRIGGERS
-- 
--
-- ----------------------------------------------------------------------------------

-- -----------------------------------------------------
-- Trigger sets board size after new game added into table.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS add_board_size;

DELIMITER ??
CREATE TRIGGER add_board_size BEFORE INSERT
ON game
FOR EACH ROW

BEGIN

	SET new.boardSize = (new.boardGridSize * new.boardGridSize);

END ??
DELIMITER ;

-- -----------------------------------------------------
-- Trigger calculates diceroll into table before entry of player's positions on turn.
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS calculate_move_roll_from_entries;

DELIMITER ??
CREATE TRIGGER calculate_move_roll_from_entries BEFORE INSERT
ON moves
FOR EACH ROW

BEGIN 
	SET new.moveRoll = (new.moveEnd - new.moveStart);

END ??
DELIMITER ;
-- -----------------------------------------------------
-- Trigger increments a player's personal & assigned game's total roll counts upon entering a new move into Moves table..
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS append_player_moves_made_total;

DELIMITER ??
CREATE TRIGGER append_player_moves_made_total AFTER INSERT
ON moves
FOR EACH ROW

BEGIN
	-- Update's player's personal stats page.
	UPDATE PlayerList 
	SET playerTotalMovesMade = playerTotalMovesMade + 1
	WHERE playerListID = (SELECT pl_PlayerListID FROM players p 
						WHERE p.playerID = (SELECT players_playerID FROM moves
						ORDER BY moveID DESC Limit 1));
	
    -- Updates the same player's stats on the game itself.
	UPDATE Players
    SET playerMovesTaken = playerMovesTaken + 1
    WHERE (playerID = (SELECT players_playerID FROM moves
						ORDER BY moveID DESC LIMIT 1)
	AND game_gameID = (SELECT game_gameID FROM moves
						ORDER BY moveID DESC LIMIT 1));
						
END ??
DELIMITER ;

-- -----------------------------------------------------
-- Trigger a move's final roll position to the specific player for current record purpose.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS assign_move_end_position_to_player_on_players_table;

DELIMITER ??
CREATE TRIGGER assign_move_end_position_to_player_on_players_table AFTER INSERT
ON moves
FOR EACH ROW

BEGIN

	DECLARE playerRollEnd INT;
    
    SET playerRollEnd = (SELECT moveEnd FROM moves
	ORDER BY moveID DESC LIMIT 1);

	UPDATE Players
	SET playerPosition = playerRollEnd WHERE playerID = (SELECT players_playerID FROM moves
		ORDER BY moveID DESC LIMIT 1);

END ??
DELIMITER ;

-- -----------------------------------------------------
-- Trigger notes whether player's roll triggered a special square (snake/ladder/boost) and assigns dedicated value tracker to true if so.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS assert_if_player_lands_on_special_square;

DELIMITER ??
CREATE TRIGGER assert_if_player_lands_on_special_square BEFORE INSERT
ON moves
FOR EACH ROW

BEGIN

	SET @moveEndPosition = new.moveStart + new.moveRoll;
	
    IF @moveEndPosition IN (SELECT snakeHead FROM snakes) 
    THEN SET new.landedOnSnake = 1;
	END IF;
        
    IF @moveEndPosition IN (SELECT ladderFoot FROM ladders)
    THEN SET new.landedOnLadder = 1;
	END IF;
    
    IF @moveEndPosition IN (SELECT boostLocation FROM boosts)
    THEN SET new.landedOnBoost = 1;    
	END IF;

END ??
DELIMITER ;

-- -----------------------------------------------------
-- Trigger marks if player won game during turn. Increments player, playerList and marks Game as complete.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS confirm_if_player_has_won_game;

DELIMITER ??
CREATE TRIGGER confirm_if_player_has_won_game AFTER INSERT
ON moves
FOR EACH ROW
	
BEGIN
	SET @moveEndPosition = new.moveStart + new.moveRoll;
    SET @winningSquareOnly = (SELECT winningSquareOnlyFeature FROM game
    WHERE gameID = (SELECT game_gameID FROM moves
    ORDER BY moveID DESC LIMIT 1));
    
    -- checks if move's final position is over game's board size AND if winning square is turned off.
    IF @moveEndPosition > (SELECT boardSize FROM game
		WHERE gameID = (SELECT game_gameID FROM moves
			ORDER BY moveID DESC LIMIT 1)) AND @winningSquareOnly = false

		
	THEN 
		CALL update_database_wins();
	
    ELSEIF @moveEndPosition = (SELECT boardSize FROM game
		WHERE gameID = (SELECT game_gameID FROM moves
			ORDER BY moveID DESC LIMIT 1)) 
            
	THEN
		CALL update_database_wins();
		
        END IF;
    
END ??
DELIMITER ;

-- -----------------------------------------------------
-- Increments a player's win count when they win a game. updates game to ended.
-- -----------------------------------------------------

DROP PROCEDURE IF EXISTS update_database_wins;

DELIMITER //
CREATE PROCEDURE update_database_wins()
BEGIN
	UPDATE Players
	SET playerWonGame = players.playerWonGame + 1 WHERE playerID = 
		(SELECT players_playerID FROM moves
	ORDER BY moveID DESC LIMIT 1);
	
	UPDATE game
		SET gameHasEnded = 1 WHERE gameID = 
			(SELECT game_gameID FROM Players WHERE playerWonGame = 1 AND playerID =
					(SELECT players_playerID FROM moves ORDER BY moveID DESC LIMIT 1));
		
	UPDATE playerList
		SET playerList.playerWinCount = playerList.playerWinCount + 1 WHERE playerListID = 
			(SELECT pl_playerListID FROM players p WHERE playerWonGame = 1 AND playerID = 
				(SELECT players_playerID FROM moves ORDER by moveID DESC LIMIT 1));
END //
DELIMITER ;
-- -----------------------------------------------------
-- Trigger increments game turn when move entry made.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS increment_game_turn_count;

DELIMITER ??
CREATE TRIGGER increment_game_turn_count AFTER INSERT
ON moves
FOR EACH ROW

BEGIN

	UPDATE game
	SET gamePlayerTurn = gamePlayerTurn + 1
	 WHERE gameID = (SELECT game_gameID FROM moves	
					ORDER BY moveID DESC LIMIT 1);
						

END ??
DELIMITER ;


-- -----------------------------------------------------
-- Trigger increments game round when turns reach player count. game turns reset to 1.
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS increment_new_game_round;

DELIMITER ??
CREATE TRIGGER increment_new_game_round AFTER INSERT
ON moves
FOR EACH ROW

BEGIN

	SET @currentGame = (SELECT game_gameID FROM moves ORDER BY moveID DESC LIMIT 1);
	SET @currentTurn = (SELECT gamePlayerTurn FROM game WHERE gameID = @currentGame);
	SET @currentPlayers = (SELECT COUNT(*) FROM players WHERE game_gameID = @currentGame);
                    
	IF @currentTurn = @currentPlayers + 1
	THEN
	UPDATE Game
		SET gameRound = gameRound + 1, gamePlayerTurn = 1 WHERE gameID = @currentGame;

	END IF;
						

END ??
DELIMITER ;


-- ----------------------------------------------------------------------------------
--
--
-- DUMMY DATA
-- 
--
-- ----------------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS insert_dummy_data;

DELIMITER !!
CREATE PROCEDURE insert_dummy_data() 
BEGIN
INSERT INTO dice (diceCount, diceFaces) VALUES (1, 6);
INSERT INTO dice (diceCount, diceFaces) VALUES (2, 6);
INSERT INTO dice (diceCount, diceFaces) VALUES (1, 10);


insert into Game(boardGridSize, boostSquarefeature, winningSquareOnlyFeature, Dice_diceID)
values ( 5, false, false, 1);
insert into Game(boardGridSize, boostSquarefeature, winningSquareOnlyFeature, Dice_diceID)
values (6,  true, false, 1);
insert into Game(boardGridSize, boostSquarefeature, winningSquareOnlyFeature, Dice_diceID)
values (10,  true, true, 2);

CALL add_new_game(50, 1, 12);

CALL add_new_snake (16,8, 1);
CALL add_new_snake (18,8, 2);
CALL add_new_snake (22,8, 3);

CALL add_new_snake (7, 3, 1);
CALL add_new_snake (9, 3, 2);
CALL add_new_snake (11, 3, 3);

CALL add_new_ladder(4, 13, 1);
CALL add_new_ladder(5, 13, 2);
CALL add_new_ladder(6, 13, 3);

CALL add_new_ladder (14, 21, 1);
CALL add_new_ladder (15, 21, 2);
CALL add_new_ladder (17, 21, 3);

CALL add_new_boost(2, 1);
CALL add_new_boost (14, 2);
CALL add_new_boost (18, 3);
CALL add_new_boost (10, 1);
CALL add_new_boost (11, 2);
CALL add_new_boost (19, 3);

INSERT INTO PlayerList(playerColour, playerWinCount) VALUES ("RED", 2);
INSERT INTO PlayerList(playerColour, playerWinCount) VALUES ("BLUE", 1);
INSERT INTO PlayerList(playerColour, playerWinCount) VALUES ("YELLOW", 4);
INSERT INTO PlayerList(playerColour, playerWinCount) VALUES ("GREEN", 5);
INSERT INTO PlayerList(playerColour, playerWinCount) VALUES ("WHITE", 5);

CALL add_new_player("Bill");

CALL add_new_player_to_game('RED', 1, 1);
CALL add_new_player_to_game('BLUE', 1, 2);
CALL add_new_player_to_game('YELLOW', 1, 3);
CALL add_new_player_to_game('RED', 2, 1);
CALL add_new_player_to_game('BLUE', 2, 3);
CALL add_new_player_to_game('RED', 3, 4);
CALL add_new_player_to_game('BLUE', 3, 3);
CALL add_new_player_to_game('RED', 4, 1);
CALL add_new_player_to_game('BLUE', 4, 3);


CALL add_player_move(0, 4, 1, 1);
CALL add_player_move(0, 5, 2, 1);
CALL add_player_move(0, 7, 3, 1);
CALL add_player_move(4, 10, 1, 1);
CALL add_player_move(5, 11, 2, 1);
CALL add_player_move(7, 11, 3, 1);
CALL add_player_move(10, 16, 1, 1);
CALL add_player_move(11, 14, 2, 1);
CALL add_player_move(11,17, 3, 1);
CALL add_player_move(16,19, 1, 1);

CALL add_player_move(0, 12, 4, 2);
CALL add_player_move(0, 7, 5, 2);
CALL add_player_move(12, 14, 4, 2);
CALL add_player_move(7, 15, 5, 2);
CALL add_player_move(14, 18, 4, 2);

CALL add_player_move(10, 15, 6, 3);
CALL add_player_move(10, 15, 7, 3);
CALL add_player_move(10, 15, 6, 3);

CALL add_player_move(0, 6, 8, 4);
CALL add_player_move(0, 5, 9, 4);
CALL add_player_move(6, 17, 8, 4);
CALL add_player_move(5, 12, 9, 4);
CALL add_player_move(17, 18, 8, 4);
CALL add_player_move(12, 50, 9, 4);

END !!

DELIMITER ;


-- ----------------------------------------------------------------------------------
--
--
--  SCRIPT & PROCEDURE TESTS
--
--
-- ----------------------------------------------------------------------------------

-- dummy data insert cannot be added if game files already exists (i.e. has been called once).
DROP PROCEDURE IF EXISTS test;

DELIMITER !!
CREATE PROCEDURE test()
BEGIN
IF (SELECT EXISTS (SELECT 1 FROM game)) = 0
    THEN
--     INSERT INTO databaseEnabled(isDatabaseOn) values (true);
		CALL insert_dummy_data;

    END IF;
END !!
DELIMITER ;


CALL test();

SELECT * FROM dice;
SELECT * FROM game;

SELECT * FROM players;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
